# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: f94541335874fdbdbb05e36a01f599d9e6ffc24509b67baf3b28fc7dc1e700021f00677e5b185189ec7ecc04014e690b618a60cc9152b12f82e4b2c5d54c5c70

test:
  secret_key_base: 8067b337c179e9338efc7621c0856499cc3cf4ba9aa7f5c7b00348a8be664748688d484f7ea975d35db16451de93ef23b54fbfe5517577b1d6e88c24f5fd7ffa

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
